icon: ':material-brain:'
cit:
  port: 3003
  health: /ping

build:
  variants:
    # NOTE: We'll link beta to latest until Immich offers a newer beta.
    - tag: latest
      containerfile: Containerfile
      default: true
      aliases: [beta]
    - tag: no-avx
      containerfile: Containerfile
      args:
        NO_AVX: "true"
      tag_desc: "**No-AVX Build**. onnxruntime compiled without AVX/AVX2/AVX512, for CPUs (or VMs/older hardware) that don't support AVX."
